import { createClient } from '@supabase/supabase-js';

// Supabase configuration from environment variables
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || '';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || '';

// Check if Supabase is enabled and configured
export const isSupabaseEnabled = import.meta.env.VITE_ENABLE_SUPABASE === 'true' && supabaseUrl && supabaseAnonKey;

// Create Supabase client
export const supabase = isSupabaseEnabled
  ? createClient(supabaseUrl, supabaseAnonKey, {
      auth: {
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
      },
    })
  : null;

// Database types (will be generated by Supabase CLI or manually defined)
export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          name: string;
          email: string;
          avatar_url: string | null;
          learning_goal: string | null;
          target_role: string | null;
          available_hours_per_week: number;
          preferred_pace: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>;
      };
      roadmaps: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          description: string | null;
          data: any; // JSONB field
          total_nodes: number;
          completed_nodes: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['roadmaps']['Row'], 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['roadmaps']['Insert']>;
      };
      notes: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          content: string;
          tags: string[];
          linked_lesson_id: string | null;
          linked_course_id: string | null;
          is_pinned: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['notes']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['notes']['Insert']>;
      };
      node_progress: {
        Row: {
          id: string;
          user_id: string;
          roadmap_id: string | null;
          node_id: string;
          status: 'available' | 'in-progress' | 'completed';
          progress: number;
          completed_at: string | null;
          actual_minutes: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['node_progress']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['node_progress']['Insert']>;
      };
      task_completions: {
        Row: {
          id: string;
          user_id: string;
          node_id: string;
          task_id: string;
          status: 'not-started' | 'in-progress' | 'completed' | 'skipped';
          score: number | null;
          user_submission: string | null;
          attempts: number;
          completed_at: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['task_completions']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['task_completions']['Insert']>;
      };
      favorites: {
        Row: {
          id: string;
          user_id: string;
          item_type: 'course' | 'lesson' | 'node';
          item_id: string;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['favorites']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['favorites']['Insert']>;
      };
      chat_messages: {
        Row: {
          id: string;
          user_id: string;
          role: 'user' | 'assistant' | 'system';
          content: string;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['chat_messages']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['chat_messages']['Insert']>;
      };
    };
  };
}
