substitutions:
  _PROJECT: isn2025-2
  _SERVICE_ACCOUNT: arthur@isn2025-2.iam.gserviceaccount.com
  _REGION: southamerica-east1
  _REPO: neuro-track-frontend
  _IMAGE: frontend
  _TAG: $SHORT_SHA

serviceAccount: projects/${_PROJECT}/serviceAccounts/${_SERVICE_ACCOUNT}
options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        gcloud auth configure-docker ${_REGION}-docker.pkg.dev -q
  - name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --build-arg VITE_YOUTUBE_API_KEY=$$YOUTUBE_KEY \
          --build-arg VITE_OPENAI_API_KEY=$$OPENAI_KEY \
          -t ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${_TAG} \
          .
    secretEnv: ['YOUTUBE_KEY', 'OPENAI_KEY']
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${_TAG}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - tag
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${_TAG}
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:latest
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${_TAG}
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:latest
images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:${_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:latest
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/vite-youtube-api-key/versions/latest
    env: 'YOUTUBE_KEY'
  - versionName: projects/$PROJECT_ID/secrets/vite-openai-api-key/versions/latest
    env: 'OPENAI_KEY'
timeout: "1200s"