name: Deploy to Remote Server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install SSH key
              uses: webfactory/ssh-agent@v0.8.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            - name: Copy files to remote server using SCP
              run: |
                  scp -o StrictHostKeyChecking=no -r ./ user@your-server-ip:/path/to/deploy/

            - name: Run remote command via SSH
              run: |
                  ssh -o StrictHostK3eyChecking=no user@your-server-ip "cd /path/to/deploy && your-command-here"