name: Frontend CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint (ESLint + Prettier)
        run: |
          npx eslint src --ext .js,.jsx,.ts,.tsx
          npx prettier --check "src/**/*.{js,jsx,ts,tsx,json,css,md}"

      - name: Run tests with coverage
        run: npm test -- --coverage --watchAll=false

      - name: Check coverage threshold
        run: |
          COVERAGE=$(jq '.total.lines.pct' coverage/coverage-summary.json)
          echo "Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 60" | bc -l) )); then
            echo "Cobertura abaixo de 60%"
            exit 1
          fi

      - name: Build React app
        run: npm run build